feat(docker-push-to-registries): Added
telicent-oss/shared-workflows pull request #3
Opened 2024-02-29 17:22 UTC by ACoolmanTelicent

2024-02-29 19:33 UTC, davec504 requested changes

2024-02-29 19:33 UTC, davec504 commented on .github/workflows/docker-push-to-registries.yml
> +            ${{ inputs.BUILD_ARGS }}
Is this necessary when the libraries it will be using will be public?

2024-02-29 19:34 UTC, rob-telicent commented on .github/workflows/docker-push-to-registries.yml
> +            ${{ env.DOCKER_USERNAME }}/${{ inputs.APP_NAME_PREFIX }}${{ inputs.APP_NAME }}${{ inputs.IMAGE_SUFFIX }}
```suggestion
            telicent/${{ inputs.APP_NAME_PREFIX }}${{ inputs.APP_NAME }}${{ inputs.IMAGE_SUFFIX }}
```
The docker username doesn't match our org name

2024-02-29 19:36 UTC, rob-telicent requested changes
Just needs a lick of sanity on the docker repo name

2024-02-29 19:41 UTC, ACoolmanTelicent commented
Whoops. NOthing has changed yet. Ignore this review for a few minutes

2024-02-29 20:03 UTC, davec504 commented on .github/workflows/docker-push-to-registries.yml
> +          The versioned AWS ECR image tag that was created and published.
```suggestion
          The versioned docker image tag that was created and published.
```

2024-03-05 09:58 UTC, tatelicent commented on .github/workflows/docker-push-to-registries.yml
> +          password: ${{ secrets.DOCKER_PASSWORD }}
Note this should only be used for images which will be public, not for private ones

2024-03-07 09:18 UTC, ACoolmanTelicent commented on .github/workflows/docker-push-to-registries.yml
> +
Note: I don't know how labels/actions do/can fit into our deployment pipeline, so I'm happy to do whatever y'all think is best

2024-03-07 09:18 UTC, merged

2024-03-07 09:21 UTC, ACoolmanTelicent commented
Hm.

So it seems like I accidentally pressed merge?

Surprising as  
1. I don't feel like I pressed anything (I literally say the PR turn purple as I was typing - maybe I hit a kb shortcut?)
2. This does not have any approvals.

Its not terrible, as the diff moves things forward.

But I'm investigating..

2024-03-07 09:23 UTC, ACoolmanTelicent commented
Oh.... ok.

So it may be because I pushed commits to this branch... from my local, directly to `telicent-oss`, and github resolved this by closing this PR.

I guess on the correct assumption I'll just open the PR in `telicent-oss`.